name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
        id: go

      - name: Build artifacts
        run: make

      - name: E2E test with TTY (we need it!)
        run: docker run -t --rm -v $(pwd):/src -w /src ubuntu:latest bash -c 'apt update -y && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends jq tzdata && ./test/test.sh'
